services:
  campus-navigate-3d-db:
    image: postgres:16
    container_name: campus-navigate-3d-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./database:/var/lib/postgresql/data

  campus-navigate-3d-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/zebaro24/campus-navigate-3d-be:latest
    container_name: campus-navigate-3d-be
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=campus-navigate-3d-db
      - SECRET_KEY
    depends_on:
      - campus-navigate-3d-db
    expose:
      - "8000"
    volumes:
      - ./models_3d:/app/models_3d
      - ./images:/app/images