# Generated by Django 5.2.1 on 2025-05-28 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='place_images/')),
                ('flight_type', models.CharField(choices=[('panorama', 'Панорама вокруг'), ('points_flight', 'Облёт по точкам'), ('free_flight', 'Свободный полёт')], default='panorama', max_length=20)),
                ('camera_view_direction', models.CharField(choices=[('inside', 'Смотреть внутрь'), ('outside', 'Смотреть наружу')], default='inside', max_length=10)),
                ('camera_height', models.FloatField(default=1.6)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.flightlocation')),
            ],
        ),
    ]
