# Generated by Django 5.2.1 on 2025-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightlocation',
            options={'verbose_name': 'Локація обльоту', 'verbose_name_plural': 'Локації обльоту'},
        ),
        migrations.AlterModelOptions(
            name='flightpoint',
            options={'ordering': ['id'], 'verbose_name': 'Точка польоту', 'verbose_name_plural': 'Точки польоту'},
        ),
        migrations.RemoveField(
            model_name='flightlocation',
            name='camera_height',
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='camera_pitch',
            field=models.FloatField(blank=True, null=True, verbose_name='Нахил камери (pitch, Y), °'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='pitch',
            field=models.FloatField(blank=True, null=True, verbose_name='Нахил (pitch, Y), °'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='position_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Позиція X'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='position_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Позиція Y'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='position_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Позиція Z'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='roll',
            field=models.FloatField(blank=True, null=True, verbose_name='Крен (roll, Z), °'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Швидкість камери'),
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='yaw',
            field=models.FloatField(blank=True, null=True, verbose_name='Азимут (yaw, X), °'),
        ),
        migrations.AddField(
            model_name='flightpoint',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='camera_view_direction',
            field=models.CharField(blank=True, choices=[('inside', 'Дивитися всередину'), ('outside', 'Дивитися назовні')], max_length=10, null=True, verbose_name='Напрямок камери'),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='flight_type',
            field=models.CharField(blank=True, choices=[('static_frame', 'Статичний кадр'), ('points_flight', 'Обліт по точках'), ('panorama', 'Панорама навколо')], default=None, max_length=20, verbose_name='Дiя камери'),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='place_images/', verbose_name='Зображення (опціонально)'),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='flightpoint',
            name='position_x',
            field=models.FloatField(verbose_name='Позиція X'),
        ),
        migrations.AlterField(
            model_name='flightpoint',
            name='position_y',
            field=models.FloatField(verbose_name='Позиція Y'),
        ),
        migrations.AlterField(
            model_name='flightpoint',
            name='position_z',
            field=models.FloatField(verbose_name='Позиція Z'),
        ),
    ]
