# Generated by Django 5.2.1 on 2025-05-30 10:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_universitymodel_alter_flightpoint_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universitymodel',
            options={'verbose_name': 'Модель університету', 'verbose_name_plural': 'Моделі університету'},
        ),
        migrations.AddField(
            model_name='flightlocation',
            name='category',
            field=models.CharField(blank=True, choices=[('static_frame', 'Статичний кадр'), ('points_flight', 'Обліт по точках'), ('panorama', 'Панорама навколо')], max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='camera_view_direction',
            field=models.CharField(blank=True, choices=[('inside', 'Дивитися всередину'), ('outside', 'Дивитися назовні'), ('direction', 'Дивитися за напрямком руху')], max_length=10, null=True, verbose_name='Напрямок камери'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна модель'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='model_file',
            field=models.FileField(upload_to=api.models.model_file_path, verbose_name='Файл моделі'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата завантаження'),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='version',
            field=models.CharField(max_length=20, unique=True, verbose_name='Версія'),
        ),
    ]
