# Generated by Django 5.2.1 on 2025-06-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_universitymodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlocation',
            name='roll',
        ),
        migrations.AlterField(
            model_name='flightlocation',
            name='category',
            field=models.CharField(blank=True, choices=[('main', 'Головна'), ('important', 'Важливі місця'), ('cabinet', 'Кабінети')], max_length=20, null=True, verbose_name='Категорія'),
        ),
    ]
