# Generated by Django 5.2.1 on 2025-06-01 23:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_flightlocation_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.image_file_path, verbose_name='Зображення (опціонально)'),
        ),
    ]
